apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app               
  namespace: argocd               
spec:
  project: guptaji-tech-web                
  
  source:
    repoURL: 'https://github.com/guptaji-tech-web/python-app.git'
    targetRevision: sit
    path: /
  
  destination:
    server: 'https://34.169.186.145'
    namespace: python-app-sit              
  
  syncPolicy:
    automated:                         
      prune: true                       
      selfHeal: true                    
    syncOptions:
      - CreateNamespace=true
