name: Enforce specific source branch

on:
  pull_request:
    branches:
      - pre-prod

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if source branch is not sit
        if: github.head_ref != 'sit'
        run: |
          echo "You can only create PRs to preprod from sit branch."
          exit 1
