name: Enforce specific source branch

on:
  pull_request:
    branches:
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if source branch is not 'pre-prod'
        if: github.head_ref != 'pre-prod'
        run: |
          echo "You can only create PRs to master from pre-prod branch."
          exit 1
