name: Enforce specific source branch

on:
  pull_request:
    branches:
      - sit

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if source branch is not 'feature'
        if: "!startsWith(github.head_ref, 'feature-')"
        run: |
          echo "You can only create PRs to sit from feature branch."
          exit 1
